In [1]:
# Metric danh gia 
from sklearn.metrics import f1_score, confusion_matrix, accuracy_score

# Ve do thi
import seaborn as sn
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np

In [4]:
y_xlmr=np.load("/content/drive/MyDrive/NLP-DS/Thực hành 1 - Sentiment analysis/y_pred_xlmr.npy")
y_pho=np.load("/content/drive/MyDrive/NLP-DS/Thực hành 1 - Sentiment analysis/y_pred_pho.npy")
y_news=np.load("/content/drive/MyDrive/NLP-DS/Thực hành 1 - Sentiment analysis/y_pred_news.npy")
y_true=np.load("/content/drive/MyDrive/NLP-DS/Thực hành 1 - Sentiment analysis/y_true.npy")

In [7]:
print("==============================XLMR========================")
cf = confusion_matrix(y_true,y_xlmr)
print(cf)

evaluation = f1_score(y_true, y_xlmr, average='micro')

print("F1 - micro: " + str(evaluation))

evaluation = f1_score(y_true, y_xlmr, average='macro')
print("F1 - macro: " + str(evaluation))

==============================XLMR========================
[[ 15  16   1   1   5   2   0]
 [ 10  79  12   5  17   6   3]
 [  0  11 137   3  26  14   2]
 [  3   5   3  32   0   3   0]
 [  1  18  17   4  72  10   7]
 [  2   7  10   4   6  87   0]
 [  0   1   6   0   4   1  25]]
F1 - micro: 0.645021645021645
F1 - macro: 0.6237469808816819


In [8]:
print("==============================PhoBERT========================")
cf = confusion_matrix(y_true,y_pho)
print(cf)

evaluation = f1_score(y_true, y_pho, average='micro')

print("F1 - micro: " + str(evaluation))

evaluation = f1_score(y_true, y_pho, average='macro')
print("F1 - macro: " + str(evaluation))

==============================PhoBERT========================
[[ 15  16   0   2   4   2   1]
 [ 16  68  14   5  18   8   3]
 [  4   7 140   3  21  14   4]
 [  3   2   3  31   4   3   0]
 [  2  13  18   0  81  12   3]
 [  1   6  11   4  13  81   0]
 [  0   3   4   0   4   1  25]]
F1 - micro: 0.6363636363636364
F1 - macro: 0.613297645968741


In [9]:
print("==============================BERT4NEWs========================")
cf = confusion_matrix(y_true,y_news)
print(cf)

evaluation = f1_score(y_true, y_news, average='micro')

print("F1 - micro: " + str(evaluation))

evaluation = f1_score(y_true, y_news, average='macro')
print("F1 - macro: " + str(evaluation))

==============================BERT4NEWs========================
[[  8  19   1   1   6   5   0]
 [  6  68  30   6  16   5   1]
 [  1  14 134   5  25  12   2]
 [  0   6   6  27   2   5   0]
 [  1  17  26   1  67  13   4]
 [  1  10  28   4  13  60   0]
 [  0   4  11   1  11   1   9]]
F1 - micro: 0.5382395382395382
F1 - macro: 0.48475428190855857


=> XLMR tốt nhất